### ISSUE TITLE
Display movie modal

### ISSUE THREAD

**Issue by rbartl2** [blakeneely/project2#10]
## User Story
As a user, I want to display the movie I have selected in an individual modal

## Acceptance Criteria
- [ ] Large movie poster appears to the left of the modal
- [ ] Additional movie info appears beside poster (i.e. Title, year, runtime, rating, director, actor, plot)
- [ ] Button to add to user watchlist (adds to database)

## Tasks
1. Use bootstrap or bulma frameworks for modal snippit
2. Use API call to:
- get movie poster img 
- get movie info
3. Add button in modal that adds movie to user's watchlist database
4. Add close button to exit modal
