### ISSUE TITLE
Display MyList layout

### ISSUE THREAD

**Issue by blakeneely** [blakeneely/project2#11]
## User Store
- As a user when I click MyList I want to see my selected movies I've stored in my Watch List

## Acceptance Criteria
- [ ] Navbar is updated to remove MyList link
- [ ] Movies from the user's database are displayed in a grid
- [ ] Each movie has a Close box to remove from database and grid

## Tasks
1. Use Bootstrap or Bulma frameworks for navbar snippet
2. Make findAll Sequelize call to database 
3. Display returned jSON into grid row of max 4 movie posters
4. Add "X" close box to each movie poster displayed in top right corner
5. Movies remove from database and grid when "X" is clicked
