### ISSUE TITLE
Add User Account Authentication

### ISSUE THREAD

**Issue by blakeneely** [blakeneely/project2#12]
## User Story
- As a user I want to log into MY account and see only the movies I have stored in my watch list database

## Acceptance Criteria
- [ ] User is able to log in by password 
- [ ] If incorrect password presented with "try again" message
- [ ] Users without accounts are allowed to "create account"
- [ ] All user info is store on database

## Tasks
1. Create input box for username
2. Create input box for password
3. Create "log in" button
4. Create GET request for user authentication
5. If input does not match return "in valid" code
6. If "in valid" is returned, display alert to try again 
7. Create link to create user account
8. Create form of inputs for username and password
9. Create "submit" button
10. When submitted create POST request to add to database
