### ISSUE TITLE
API Movie Call

### ISSUE THREAD

**Issue by rbartl2** [blakeneely/project2#7]
## User Story
- As a user I want to search for a movie and view information about that movie

## Acceptance Criteria
- [ ] Have APIs necessary for calls
- [ ] Receive complete responses back from API calls
- [ ] Store results in database if necessary

## Tasks
1. Find APIs that meet our needs
2. Research API docs for call method and response
3. Write GET request and log response
4. Make loop to iterate through result to display movie title, movie poster, year, actor(s), plot, rating, and trailer link
5. Display results on HTML
6. Store on movie database if checked
