### ISSUE TITLE
HTML layout

### ISSUE THREAD

**Issue by blakeneely** [blakeneely/project2#8]
## User Story
- As a user I want to see a simple yet sleek design that easily draws me in to what is most important (searching for actors/actresses or movies)

## Acceptance Criteria
- [ ] Is fully mobile responsive
- [ ] Has hero at top with rounded search bar within
- [ ] Has Navbar with elegant logo in top left and MyList link in top right
- [ ] Is displaying trending movie posters below 3 to a row
- [ ] Clicking movie posters runs movie search function

## Tasks
1. Use Bootstrap or Bulma frameworks to ease of mobile responsiveness
2. Grab and place code snippet from framework for hero element
3. Use image as hero background
4. Grab and place code snippet from framework for navbar element
5. Remove all navbar elements except for logo and 1 link
6. Grab and place code snippet from framework for search bar into center of hero
7. Build grid for movie poster placement from API call below hero
