### ISSUE TITLE
Actor/Actress Search Layout

### ISSUE THREAD

**Issue by blakeneely** [blakeneely/project2#9]
## User Story
- As a user I want to see actor's movies I've search for displayed in a simple design

## Acceptance Criteria
- [ ] Actor's name appears in large at the top
- [ ] Movie posters display in a grid below actor's name sorted by year
- [ ] Movie posters are links to run movie search function
- [ ] Navbar changes to include search bar within

## Tasks
1. Write on-click event listener for search function
2. On click: display new search result view
3. Search box moves to navbar
4. Movie posters display in max 5 across row grid sorted by year (newest first)
5. Movie posters are links that run movie search function and display in modal
